my:
  greeting: Hello World from the RocknRoll User-Service in GitHub env DKR

spring:
  sql:
    init:
      mode: never
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://host.docker.internal:3307/rnralbumart
#    url: jdbc:mysql://localhost:3306/rnralbumart
    username: root
    password: password
  application:
    name: rnr-user-service

  config:
    import:
      - optional:configserver:http://rnr-config-server:8888

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    defer-datasource-initialization: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql : true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    eureka-connection-idle-timeout-seconds: 60
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/
